from setuptools import find_packages, setup

setup(
    name="HMI_project",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    python_requires=">=3.9",
    install_requires=[
        "pandas>=2.0.0",
        "numpy>=1.24.3",
        "nltk>=3.8.1",
        "scikit-learn>=1.2.2",
        "transformers>=4.28.1",
        "matplotlib>=3.7.1",
        "seaborn>=0.12.2",
        "plotly>=5.14.1",
        "networkx>=3.1",
        "beautifulsoup4>=4.12.2",
        "wordcloud>=1.8.2.2",
        "loguru>=0.7.0",
        "tqdm>=4.65.0",
        "sompy-package",
    ],
    extras_require={
        "dev": [
            "ruff>=0.0.262",
            "isort>=5.12.0",
            "black>=23.3.0",
            "mypy>=1.2.0",
            "pytest>=7.3.1",
            "pytest-cov>=4.1.0",
            "pytest-mock>=3.10.0",
            "sphinx>=6.1.3",
            "sphinx-rtd-theme>=1.2.0",
            "sphinx-autodoc-typehints>=1.22.0",
            "pre-commit>=3.2.2",
            "build>=0.10.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "enron-pipeline=src.main:main",
        ],
    },
    description="A comprehensive pipeline for analyzing the Enron email dataset",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 1 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Information Analysis",
    ],
)
